[package]
name = "treemath"
version = "0.2.0"
edition = "2024"
license = "Apache-2.0"
authors = ["Beltram Maldant"]
description = "Arithmetics for perfect binary trees"
keywords = ["tree"]
documentation = "https://docs.rs/treemath"
repository = "https://github.com/beltram/treemath"
homepage = "https://github.com/beltram/treemath"
resolver = "3"

[dev-dependencies]
treemath = { path = ".", features = ["bench"] }
criterion = { package = "codspeed-criterion-compat", version = "*" }
rand = "0.9"
itertools = "0.14"

[[bench]]
name = "all"
harness = false

[[bench]]
name = "level"
harness = false

[[bench]]
name = "root"
harness = false

[[bench]]
name = "parent"
harness = false

[[bench]]
name = "sibling"
harness = false

[[bench]]
name = "left_right"
harness = false

[[bench]]
name = "direct_path"
harness = false

[[bench]]
name = "copath"
harness = false

[[bench]]
name = "common_ancestor"
harness = false

[features]
bench = []
